 # Setup
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-sitemap
  - jemoji

include:
  - "_pages"

exclude:
  - "README.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"

# Geocamp Data

title: Geocamp 2019 Valencia
email: info@geocamp.es

description: >
  Geocamp 2019, Valencia 15/16 de Junio.

author: Geoinquietos VLC
twitter_username: geocampes
github_username:  geocamp-es

header_logo: assets/imgs/favicons/favicon_114.png


header_pages:
  - _pages/equipo.md
  - _pages/coc.md
  - _pages/anteriores.md

minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    twitter: geocampes
    github:  geocamp-es
    rss: rss
    instagram: '#geocampes'
    telegram: '@geocampes'


